// Single entry point for all API functions: import { login, register } from "../api";
export { apiRequest } from "./client";
export * from "./auth.js";
export * from "./Checkin.js";
export * from "./housekeeping.js";
export * from "./foodorder.js";
export * from "./checkout.js";
export * from "./room.js";
export * from "./settings.js";
export * from "./dashboard.js";
export * from "./guest.js";
export * from "./booking.js";
export * from "./invoice.js";
export * from "./report.js";
export * from "./hotelProfile.js";
